---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafaka-n1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafaka-n1
  template:
    metadata:
      labels:
        app: kafaka-n1
    spec:
      hostname: kafaka-n1
      volumes:
        - name: kafaka-data
          hostPath:
            path: /data/kafaka-standalone/kafaka-data-n1
        - name: kafka-log
          hostPath:
            path: /data/kafaka-standalone/kafka-log-n1
      dnsPolicy: ClusterFirst
      containers:
        - name: kafaka-n1
          image: wurstmeister/kafka:1.0.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: kafaka-data
              readOnly: false
              mountPath: "/kafka"
            - name: kafka-log
              readOnly: false
              mountPath: "/opt/kafka/logs"
          ports:
            - containerPort: 9092
            - containerPort: 1099
          env:
            # broker ID,必须要有,各节点不能一致
            - name: KAFKA_BROKER_ID
              value: "1"
              # 必须要有,zk集群
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zk-n1:2181/kafka
              # 必须要有,kafka工作端口
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
              # 可选
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafaka-n1
              # 可选
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx4G -Xms4G"
              # JMX相关，可选
            - name: KAFKA_JMX_OPTS
              value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
              # JMX相关，可选
            - name: JMX_PORT
              value: "1099"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafaka-n1
  name: kafaka-n1
  namespace: default
spec:
  clusterIP: None
  ports:
    - port: 9092
      protocol: TCP
      targetPort: 9092
      name: kafka
    - port: 1099
      protocol: TCP
      targetPort: 1099
      name: jmx
  selector:
    app: kafaka-n1
  sessionAffinity: None
  type: ClusterIP