apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-3
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-4
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-5
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200M
